<Project Sdk="Microsoft.NET.Sdk">

	<ItemGroup>
		<PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.14.0" />
		<PackageReference Include="Microsoft.Extensions.Configuration" Version="10.0.0" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Domain\Domain.csproj" />
		<ProjectReference Include="..\SharedKernel\SharedKernel.csproj" />
	</ItemGroup>

	<PropertyGroup>
		<Nullable>enable</Nullable>
		<TargetFramework>net9.0</TargetFramework>
		<!--<ImplicitUsings>enable</ImplicitUsings>-->
	</PropertyGroup>

</Project>