<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<Nullable>enable</Nullable>
		<TargetFramework>net9.0</TargetFramework>
		<!--<ImplicitUsings>enable</ImplicitUsings>-->
	</PropertyGroup>

	<ItemGroup>
		<Compile Update="Shared\Resources\DataDictionary.Designer.cs">
			<DesignTime>True</DesignTime>
			<AutoGen>True</AutoGen>
			<DependentUpon>DataDictionary.resx</DependentUpon>
		</Compile>
		<Compile Update="Shared\Resources\Messages\Validations.Designer.cs">
			<DesignTime>True</DesignTime>
			<AutoGen>True</AutoGen>
			<DependentUpon>Validations.resx</DependentUpon>
		</Compile>
	</ItemGroup>

	<ItemGroup>
		<EmbeddedResource Update="Shared\Resources\ButtonCaptions.resx">
			<Generator>PublicResXFileCodeGenerator</Generator>
			<LastGenOutput>ButtonCaptions.Designer.cs</LastGenOutput>
		</EmbeddedResource>
		<EmbeddedResource Update="Shared\Resources\DataDictionary.resx">
			<Generator>PublicResXFileCodeGenerator</Generator>
			<LastGenOutput>DataDictionary.Designer.cs</LastGenOutput>
		</EmbeddedResource>
		<EmbeddedResource Update="Shared\Resources\Messages\Errors.resx">
			<Generator>PublicResXFileCodeGenerator</Generator>
			<LastGenOutput>Errors.Designer.cs</LastGenOutput>
		</EmbeddedResource>
		<EmbeddedResource Update="Shared\Resources\Messages\Successes.resx">
			<Generator>PublicResXFileCodeGenerator</Generator>
			<LastGenOutput>Successes.Designer.cs</LastGenOutput>
		</EmbeddedResource>
		<EmbeddedResource Update="Shared\Resources\Messages\Validations.resx">
			<Generator>PublicResXFileCodeGenerator</Generator>
			<LastGenOutput>Validations.Designer.cs</LastGenOutput>
		</EmbeddedResource>
		<EmbeddedResource Update="Shared\Resources\PageTitles.resx">
			<Generator>PublicResXFileCodeGenerator</Generator>
			<LastGenOutput>PageTitles.Designer.cs</LastGenOutput>
		</EmbeddedResource>
	</ItemGroup>

</Project>